# Generated by Django 4.2 on 2023-05-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bwf', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Match', max_length=25),
        ),
    ]
