# Generated by Django 4.2 on 2023-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bwf', '0003_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
